site_name: moo-rs
site_author: Andr√©s Sandoval
site_description: Multi-objective optimization using genetic algorithms in Rust and Python.
use_directory_urls: false

theme:
  language: en
  logo: images/moors-logo.png
  favicon: images/moors-logo.png
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: black
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: black
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  highlightjs: true
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  - navigation.indexes
  - content.tooltips
  - navigation.path
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - navigation.tabs
  - navigation.footer
repo_url: https://github.com/andresliszt/moo-rs
repo_name: "andresliszt/moo-rs"

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
  - pymdownx.arithmatex:
      generic: true
  - neoteroi.cards
  - neoteroi.timeline
  - neoteroi.projects
extra_javascript:
  - js/custom_mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

nav:
  - üè† Home: index.md
  - üöÄ Getting Started:
       - pymoors:
          - Installation: getting_started_pymoors/installation.md
          - Knapsack Problem: getting_started_pymoors/knapsack.ipynb
          - Small Real Valued Problem: getting_started_pymoors/real_valued.ipynb
  - üíª Development: development.md
  - üìñ User Guide Pymoors:
      - Fitness and Constraints: user_guide/fitness_and_constraints/index.md
      - Genetic Operators: user_guide/operators.md
      - Duplicates Cleaner: user_guide/duplicates.md
      - Algorithms:
        - Introduction: user_guide/algorithms/algorithms.ipynb
        - NSGA-II: user_guide/algorithms/nsga2.ipynb
        - RNSGA-II: user_guide/algorithms/rnsga2.ipynb
        - NSGA-III: user_guide/algorithms/nsga3.ipynb
        - AGE-MOEA: user_guide/algorithms/agemoea.ipynb
        - REVEA: user_guide/algorithms/revea.ipynb
        - SPEA-II: user_guide/algorithms/spea2.ipynb

plugins:
    - mkdocs-jupyter
    - search
    - include-markdown
